/********************************************************************************
** Form generated from reading UI file 'gamewindow.ui'
**
** Created by: Qt User Interface Compiler version 4.8.6
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_GAMEWINDOW_H
#define UI_GAMEWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QHeaderView>
#include <QtGui/QLineEdit>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QPushButton>
#include <QtGui/QStatusBar>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_GameWindow
{
public:
    QAction *actionNew_Game;
    QAction *actionSave;
    QAction *actionSave_and_Exit;
    QAction *actionExit;
    QAction *actionHow_To_Play;
    QWidget *centralwidget;
    QLineEdit *cell_0_0;
    QLineEdit *cell_0_1;
    QLineEdit *cell_0_2;
    QLineEdit *cell_0_3;
    QLineEdit *cell_0_4;
    QLineEdit *cell_0_5;
    QLineEdit *cell_0_6;
    QLineEdit *cell_0_7;
    QLineEdit *cell_0_8;
    QLineEdit *cell_1_6;
    QLineEdit *cell_1_0;
    QLineEdit *cell_1_1;
    QLineEdit *cell_1_2;
    QLineEdit *cell_1_7;
    QLineEdit *cell_1_4;
    QLineEdit *cell_1_8;
    QLineEdit *cell_1_3;
    QLineEdit *cell_1_5;
    QLineEdit *cell_2_6;
    QLineEdit *cell_2_0;
    QLineEdit *cell_2_1;
    QLineEdit *cell_2_2;
    QLineEdit *cell_2_7;
    QLineEdit *cell_2_4;
    QLineEdit *cell_2_8;
    QLineEdit *cell_2_3;
    QLineEdit *cell_2_5;
    QLineEdit *cell_3_5;
    QLineEdit *cell_3_0;
    QLineEdit *cell_4_0;
    QLineEdit *cell_5_2;
    QLineEdit *cell_3_1;
    QLineEdit *cell_3_3;
    QLineEdit *cell_4_5;
    QLineEdit *cell_4_2;
    QLineEdit *cell_5_5;
    QLineEdit *cell_5_7;
    QLineEdit *cell_3_6;
    QLineEdit *cell_4_6;
    QLineEdit *cell_4_4;
    QLineEdit *cell_5_0;
    QLineEdit *cell_5_4;
    QLineEdit *cell_4_1;
    QLineEdit *cell_3_7;
    QLineEdit *cell_3_2;
    QLineEdit *cell_4_3;
    QLineEdit *cell_5_8;
    QLineEdit *cell_4_7;
    QLineEdit *cell_4_8;
    QLineEdit *cell_3_4;
    QLineEdit *cell_3_8;
    QLineEdit *cell_5_1;
    QLineEdit *cell_5_3;
    QLineEdit *cell_5_6;
    QLineEdit *cell_6_5;
    QLineEdit *cell_6_0;
    QLineEdit *cell_7_0;
    QLineEdit *cell_8_2;
    QLineEdit *cell_6_1;
    QLineEdit *cell_6_3;
    QLineEdit *cell_7_5;
    QLineEdit *cell_7_2;
    QLineEdit *cell_8_5;
    QLineEdit *cell_8_7;
    QLineEdit *cell_6_6;
    QLineEdit *cell_7_6;
    QLineEdit *cell_7_4;
    QLineEdit *cell_8_0;
    QLineEdit *cell_8_4;
    QLineEdit *cell_7_1;
    QLineEdit *cell_6_7;
    QLineEdit *cell_6_2;
    QLineEdit *cell_7_3;
    QLineEdit *cell_8_8;
    QLineEdit *cell_7_7;
    QLineEdit *cell_7_8;
    QLineEdit *cell_6_4;
    QLineEdit *cell_6_8;
    QLineEdit *cell_8_1;
    QLineEdit *cell_8_3;
    QLineEdit *cell_8_6;
    QFrame *line;
    QFrame *line_3;
    QFrame *line_4;
    QFrame *line_2;
    QPushButton *backButton;
    QMenuBar *menubar;
    QMenu *menuFile;
    QMenu *menuHelp;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *GameWindow)
    {
        if (GameWindow->objectName().isEmpty())
            GameWindow->setObjectName(QString::fromUtf8("GameWindow"));
        GameWindow->resize(562, 600);
        GameWindow->setStyleSheet(QString::fromUtf8(""));
        actionNew_Game = new QAction(GameWindow);
        actionNew_Game->setObjectName(QString::fromUtf8("actionNew_Game"));
        actionSave = new QAction(GameWindow);
        actionSave->setObjectName(QString::fromUtf8("actionSave"));
        actionSave_and_Exit = new QAction(GameWindow);
        actionSave_and_Exit->setObjectName(QString::fromUtf8("actionSave_and_Exit"));
        actionExit = new QAction(GameWindow);
        actionExit->setObjectName(QString::fromUtf8("actionExit"));
        actionHow_To_Play = new QAction(GameWindow);
        actionHow_To_Play->setObjectName(QString::fromUtf8("actionHow_To_Play"));
        centralwidget = new QWidget(GameWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        cell_0_0 = new QLineEdit(centralwidget);
        cell_0_0->setObjectName(QString::fromUtf8("cell_0_0"));
        cell_0_0->setGeometry(QRect(50, 30, 40, 40));
        cell_0_0->setMaxLength(1);
        cell_0_0->setAlignment(Qt::AlignCenter);
        cell_0_1 = new QLineEdit(centralwidget);
        cell_0_1->setObjectName(QString::fromUtf8("cell_0_1"));
        cell_0_1->setGeometry(QRect(100, 30, 40, 40));
        cell_0_1->setMaxLength(1);
        cell_0_1->setAlignment(Qt::AlignCenter);
        cell_0_2 = new QLineEdit(centralwidget);
        cell_0_2->setObjectName(QString::fromUtf8("cell_0_2"));
        cell_0_2->setGeometry(QRect(150, 30, 40, 40));
        cell_0_2->setMaxLength(1);
        cell_0_2->setAlignment(Qt::AlignCenter);
        cell_0_3 = new QLineEdit(centralwidget);
        cell_0_3->setObjectName(QString::fromUtf8("cell_0_3"));
        cell_0_3->setGeometry(QRect(210, 30, 40, 40));
        cell_0_3->setMaxLength(1);
        cell_0_3->setAlignment(Qt::AlignCenter);
        cell_0_4 = new QLineEdit(centralwidget);
        cell_0_4->setObjectName(QString::fromUtf8("cell_0_4"));
        cell_0_4->setGeometry(QRect(260, 30, 40, 40));
        cell_0_4->setMaxLength(1);
        cell_0_4->setAlignment(Qt::AlignCenter);
        cell_0_5 = new QLineEdit(centralwidget);
        cell_0_5->setObjectName(QString::fromUtf8("cell_0_5"));
        cell_0_5->setGeometry(QRect(310, 30, 40, 40));
        cell_0_5->setMaxLength(1);
        cell_0_5->setAlignment(Qt::AlignCenter);
        cell_0_6 = new QLineEdit(centralwidget);
        cell_0_6->setObjectName(QString::fromUtf8("cell_0_6"));
        cell_0_6->setGeometry(QRect(370, 30, 40, 40));
        cell_0_6->setMaxLength(1);
        cell_0_6->setAlignment(Qt::AlignCenter);
        cell_0_7 = new QLineEdit(centralwidget);
        cell_0_7->setObjectName(QString::fromUtf8("cell_0_7"));
        cell_0_7->setGeometry(QRect(420, 30, 40, 40));
        cell_0_7->setMaxLength(1);
        cell_0_7->setAlignment(Qt::AlignCenter);
        cell_0_8 = new QLineEdit(centralwidget);
        cell_0_8->setObjectName(QString::fromUtf8("cell_0_8"));
        cell_0_8->setGeometry(QRect(470, 30, 40, 40));
        cell_0_8->setMaxLength(1);
        cell_0_8->setAlignment(Qt::AlignCenter);
        cell_1_6 = new QLineEdit(centralwidget);
        cell_1_6->setObjectName(QString::fromUtf8("cell_1_6"));
        cell_1_6->setGeometry(QRect(370, 80, 40, 40));
        cell_1_6->setMaxLength(1);
        cell_1_6->setAlignment(Qt::AlignCenter);
        cell_1_0 = new QLineEdit(centralwidget);
        cell_1_0->setObjectName(QString::fromUtf8("cell_1_0"));
        cell_1_0->setGeometry(QRect(50, 80, 40, 40));
        cell_1_0->setMaxLength(1);
        cell_1_0->setAlignment(Qt::AlignCenter);
        cell_1_1 = new QLineEdit(centralwidget);
        cell_1_1->setObjectName(QString::fromUtf8("cell_1_1"));
        cell_1_1->setGeometry(QRect(100, 80, 40, 40));
        cell_1_1->setMaxLength(1);
        cell_1_1->setAlignment(Qt::AlignCenter);
        cell_1_2 = new QLineEdit(centralwidget);
        cell_1_2->setObjectName(QString::fromUtf8("cell_1_2"));
        cell_1_2->setGeometry(QRect(150, 80, 40, 40));
        cell_1_2->setMaxLength(1);
        cell_1_2->setAlignment(Qt::AlignCenter);
        cell_1_7 = new QLineEdit(centralwidget);
        cell_1_7->setObjectName(QString::fromUtf8("cell_1_7"));
        cell_1_7->setGeometry(QRect(420, 80, 40, 40));
        cell_1_7->setMaxLength(1);
        cell_1_7->setAlignment(Qt::AlignCenter);
        cell_1_4 = new QLineEdit(centralwidget);
        cell_1_4->setObjectName(QString::fromUtf8("cell_1_4"));
        cell_1_4->setGeometry(QRect(260, 80, 40, 40));
        cell_1_4->setMaxLength(1);
        cell_1_4->setAlignment(Qt::AlignCenter);
        cell_1_8 = new QLineEdit(centralwidget);
        cell_1_8->setObjectName(QString::fromUtf8("cell_1_8"));
        cell_1_8->setGeometry(QRect(470, 80, 40, 40));
        cell_1_8->setMaxLength(1);
        cell_1_8->setAlignment(Qt::AlignCenter);
        cell_1_3 = new QLineEdit(centralwidget);
        cell_1_3->setObjectName(QString::fromUtf8("cell_1_3"));
        cell_1_3->setGeometry(QRect(210, 80, 40, 40));
        cell_1_3->setMaxLength(1);
        cell_1_3->setAlignment(Qt::AlignCenter);
        cell_1_5 = new QLineEdit(centralwidget);
        cell_1_5->setObjectName(QString::fromUtf8("cell_1_5"));
        cell_1_5->setGeometry(QRect(310, 80, 40, 40));
        cell_1_5->setMaxLength(1);
        cell_1_5->setAlignment(Qt::AlignCenter);
        cell_2_6 = new QLineEdit(centralwidget);
        cell_2_6->setObjectName(QString::fromUtf8("cell_2_6"));
        cell_2_6->setGeometry(QRect(370, 130, 40, 40));
        cell_2_6->setMaxLength(1);
        cell_2_6->setAlignment(Qt::AlignCenter);
        cell_2_0 = new QLineEdit(centralwidget);
        cell_2_0->setObjectName(QString::fromUtf8("cell_2_0"));
        cell_2_0->setGeometry(QRect(50, 130, 40, 40));
        cell_2_0->setMaxLength(1);
        cell_2_0->setAlignment(Qt::AlignCenter);
        cell_2_1 = new QLineEdit(centralwidget);
        cell_2_1->setObjectName(QString::fromUtf8("cell_2_1"));
        cell_2_1->setGeometry(QRect(100, 130, 40, 40));
        cell_2_1->setMaxLength(1);
        cell_2_1->setAlignment(Qt::AlignCenter);
        cell_2_2 = new QLineEdit(centralwidget);
        cell_2_2->setObjectName(QString::fromUtf8("cell_2_2"));
        cell_2_2->setGeometry(QRect(150, 130, 40, 40));
        cell_2_2->setMaxLength(1);
        cell_2_2->setAlignment(Qt::AlignCenter);
        cell_2_7 = new QLineEdit(centralwidget);
        cell_2_7->setObjectName(QString::fromUtf8("cell_2_7"));
        cell_2_7->setGeometry(QRect(420, 130, 40, 40));
        cell_2_7->setMaxLength(1);
        cell_2_7->setAlignment(Qt::AlignCenter);
        cell_2_4 = new QLineEdit(centralwidget);
        cell_2_4->setObjectName(QString::fromUtf8("cell_2_4"));
        cell_2_4->setGeometry(QRect(260, 130, 40, 40));
        cell_2_4->setMaxLength(1);
        cell_2_4->setAlignment(Qt::AlignCenter);
        cell_2_8 = new QLineEdit(centralwidget);
        cell_2_8->setObjectName(QString::fromUtf8("cell_2_8"));
        cell_2_8->setGeometry(QRect(470, 130, 40, 40));
        cell_2_8->setMaxLength(1);
        cell_2_8->setAlignment(Qt::AlignCenter);
        cell_2_3 = new QLineEdit(centralwidget);
        cell_2_3->setObjectName(QString::fromUtf8("cell_2_3"));
        cell_2_3->setGeometry(QRect(210, 130, 40, 40));
        cell_2_3->setMaxLength(1);
        cell_2_3->setAlignment(Qt::AlignCenter);
        cell_2_5 = new QLineEdit(centralwidget);
        cell_2_5->setObjectName(QString::fromUtf8("cell_2_5"));
        cell_2_5->setGeometry(QRect(310, 130, 40, 40));
        cell_2_5->setMaxLength(1);
        cell_2_5->setAlignment(Qt::AlignCenter);
        cell_3_5 = new QLineEdit(centralwidget);
        cell_3_5->setObjectName(QString::fromUtf8("cell_3_5"));
        cell_3_5->setGeometry(QRect(310, 190, 40, 40));
        cell_3_5->setMaxLength(1);
        cell_3_5->setAlignment(Qt::AlignCenter);
        cell_3_0 = new QLineEdit(centralwidget);
        cell_3_0->setObjectName(QString::fromUtf8("cell_3_0"));
        cell_3_0->setGeometry(QRect(50, 190, 40, 40));
        cell_3_0->setMaxLength(1);
        cell_3_0->setAlignment(Qt::AlignCenter);
        cell_4_0 = new QLineEdit(centralwidget);
        cell_4_0->setObjectName(QString::fromUtf8("cell_4_0"));
        cell_4_0->setGeometry(QRect(50, 240, 40, 40));
        cell_4_0->setMaxLength(1);
        cell_4_0->setAlignment(Qt::AlignCenter);
        cell_5_2 = new QLineEdit(centralwidget);
        cell_5_2->setObjectName(QString::fromUtf8("cell_5_2"));
        cell_5_2->setGeometry(QRect(150, 290, 40, 40));
        cell_5_2->setMaxLength(1);
        cell_5_2->setAlignment(Qt::AlignCenter);
        cell_3_1 = new QLineEdit(centralwidget);
        cell_3_1->setObjectName(QString::fromUtf8("cell_3_1"));
        cell_3_1->setGeometry(QRect(100, 190, 40, 40));
        cell_3_1->setMaxLength(1);
        cell_3_1->setAlignment(Qt::AlignCenter);
        cell_3_3 = new QLineEdit(centralwidget);
        cell_3_3->setObjectName(QString::fromUtf8("cell_3_3"));
        cell_3_3->setGeometry(QRect(210, 190, 40, 40));
        cell_3_3->setMaxLength(1);
        cell_3_3->setAlignment(Qt::AlignCenter);
        cell_4_5 = new QLineEdit(centralwidget);
        cell_4_5->setObjectName(QString::fromUtf8("cell_4_5"));
        cell_4_5->setGeometry(QRect(310, 240, 40, 40));
        cell_4_5->setMaxLength(1);
        cell_4_5->setAlignment(Qt::AlignCenter);
        cell_4_2 = new QLineEdit(centralwidget);
        cell_4_2->setObjectName(QString::fromUtf8("cell_4_2"));
        cell_4_2->setGeometry(QRect(150, 240, 40, 40));
        cell_4_2->setMaxLength(1);
        cell_4_2->setAlignment(Qt::AlignCenter);
        cell_5_5 = new QLineEdit(centralwidget);
        cell_5_5->setObjectName(QString::fromUtf8("cell_5_5"));
        cell_5_5->setGeometry(QRect(310, 290, 40, 40));
        cell_5_5->setMaxLength(1);
        cell_5_5->setAlignment(Qt::AlignCenter);
        cell_5_7 = new QLineEdit(centralwidget);
        cell_5_7->setObjectName(QString::fromUtf8("cell_5_7"));
        cell_5_7->setGeometry(QRect(420, 290, 40, 40));
        cell_5_7->setMaxLength(1);
        cell_5_7->setAlignment(Qt::AlignCenter);
        cell_3_6 = new QLineEdit(centralwidget);
        cell_3_6->setObjectName(QString::fromUtf8("cell_3_6"));
        cell_3_6->setGeometry(QRect(370, 190, 40, 40));
        cell_3_6->setMaxLength(1);
        cell_3_6->setAlignment(Qt::AlignCenter);
        cell_4_6 = new QLineEdit(centralwidget);
        cell_4_6->setObjectName(QString::fromUtf8("cell_4_6"));
        cell_4_6->setGeometry(QRect(370, 240, 40, 40));
        cell_4_6->setMaxLength(1);
        cell_4_6->setAlignment(Qt::AlignCenter);
        cell_4_4 = new QLineEdit(centralwidget);
        cell_4_4->setObjectName(QString::fromUtf8("cell_4_4"));
        cell_4_4->setGeometry(QRect(260, 240, 40, 40));
        cell_4_4->setMaxLength(1);
        cell_4_4->setAlignment(Qt::AlignCenter);
        cell_5_0 = new QLineEdit(centralwidget);
        cell_5_0->setObjectName(QString::fromUtf8("cell_5_0"));
        cell_5_0->setGeometry(QRect(50, 290, 40, 40));
        cell_5_0->setMaxLength(1);
        cell_5_0->setAlignment(Qt::AlignCenter);
        cell_5_4 = new QLineEdit(centralwidget);
        cell_5_4->setObjectName(QString::fromUtf8("cell_5_4"));
        cell_5_4->setGeometry(QRect(260, 290, 40, 40));
        cell_5_4->setMaxLength(1);
        cell_5_4->setAlignment(Qt::AlignCenter);
        cell_4_1 = new QLineEdit(centralwidget);
        cell_4_1->setObjectName(QString::fromUtf8("cell_4_1"));
        cell_4_1->setGeometry(QRect(100, 240, 40, 40));
        cell_4_1->setMaxLength(1);
        cell_4_1->setAlignment(Qt::AlignCenter);
        cell_3_7 = new QLineEdit(centralwidget);
        cell_3_7->setObjectName(QString::fromUtf8("cell_3_7"));
        cell_3_7->setGeometry(QRect(420, 190, 40, 40));
        cell_3_7->setMaxLength(1);
        cell_3_7->setAlignment(Qt::AlignCenter);
        cell_3_2 = new QLineEdit(centralwidget);
        cell_3_2->setObjectName(QString::fromUtf8("cell_3_2"));
        cell_3_2->setGeometry(QRect(150, 190, 40, 40));
        cell_3_2->setMaxLength(1);
        cell_3_2->setAlignment(Qt::AlignCenter);
        cell_4_3 = new QLineEdit(centralwidget);
        cell_4_3->setObjectName(QString::fromUtf8("cell_4_3"));
        cell_4_3->setGeometry(QRect(210, 240, 40, 40));
        cell_4_3->setMaxLength(1);
        cell_4_3->setAlignment(Qt::AlignCenter);
        cell_5_8 = new QLineEdit(centralwidget);
        cell_5_8->setObjectName(QString::fromUtf8("cell_5_8"));
        cell_5_8->setGeometry(QRect(470, 290, 40, 40));
        cell_5_8->setMaxLength(1);
        cell_5_8->setAlignment(Qt::AlignCenter);
        cell_4_7 = new QLineEdit(centralwidget);
        cell_4_7->setObjectName(QString::fromUtf8("cell_4_7"));
        cell_4_7->setGeometry(QRect(420, 240, 40, 40));
        cell_4_7->setMaxLength(1);
        cell_4_7->setAlignment(Qt::AlignCenter);
        cell_4_8 = new QLineEdit(centralwidget);
        cell_4_8->setObjectName(QString::fromUtf8("cell_4_8"));
        cell_4_8->setGeometry(QRect(470, 240, 40, 40));
        cell_4_8->setMaxLength(1);
        cell_4_8->setAlignment(Qt::AlignCenter);
        cell_3_4 = new QLineEdit(centralwidget);
        cell_3_4->setObjectName(QString::fromUtf8("cell_3_4"));
        cell_3_4->setGeometry(QRect(260, 190, 40, 40));
        cell_3_4->setMaxLength(1);
        cell_3_4->setAlignment(Qt::AlignCenter);
        cell_3_8 = new QLineEdit(centralwidget);
        cell_3_8->setObjectName(QString::fromUtf8("cell_3_8"));
        cell_3_8->setGeometry(QRect(470, 190, 40, 40));
        cell_3_8->setMaxLength(1);
        cell_3_8->setAlignment(Qt::AlignCenter);
        cell_5_1 = new QLineEdit(centralwidget);
        cell_5_1->setObjectName(QString::fromUtf8("cell_5_1"));
        cell_5_1->setGeometry(QRect(100, 290, 40, 40));
        cell_5_1->setMaxLength(1);
        cell_5_1->setAlignment(Qt::AlignCenter);
        cell_5_3 = new QLineEdit(centralwidget);
        cell_5_3->setObjectName(QString::fromUtf8("cell_5_3"));
        cell_5_3->setGeometry(QRect(210, 290, 40, 40));
        cell_5_3->setMaxLength(1);
        cell_5_3->setAlignment(Qt::AlignCenter);
        cell_5_6 = new QLineEdit(centralwidget);
        cell_5_6->setObjectName(QString::fromUtf8("cell_5_6"));
        cell_5_6->setGeometry(QRect(370, 290, 40, 40));
        cell_5_6->setMaxLength(1);
        cell_5_6->setAlignment(Qt::AlignCenter);
        cell_6_5 = new QLineEdit(centralwidget);
        cell_6_5->setObjectName(QString::fromUtf8("cell_6_5"));
        cell_6_5->setGeometry(QRect(310, 350, 40, 40));
        cell_6_5->setMaxLength(1);
        cell_6_5->setAlignment(Qt::AlignCenter);
        cell_6_0 = new QLineEdit(centralwidget);
        cell_6_0->setObjectName(QString::fromUtf8("cell_6_0"));
        cell_6_0->setGeometry(QRect(50, 350, 40, 40));
        cell_6_0->setMaxLength(1);
        cell_6_0->setAlignment(Qt::AlignCenter);
        cell_7_0 = new QLineEdit(centralwidget);
        cell_7_0->setObjectName(QString::fromUtf8("cell_7_0"));
        cell_7_0->setGeometry(QRect(50, 400, 40, 40));
        cell_7_0->setMaxLength(1);
        cell_7_0->setAlignment(Qt::AlignCenter);
        cell_8_2 = new QLineEdit(centralwidget);
        cell_8_2->setObjectName(QString::fromUtf8("cell_8_2"));
        cell_8_2->setGeometry(QRect(150, 450, 40, 40));
        cell_8_2->setMaxLength(1);
        cell_8_2->setAlignment(Qt::AlignCenter);
        cell_6_1 = new QLineEdit(centralwidget);
        cell_6_1->setObjectName(QString::fromUtf8("cell_6_1"));
        cell_6_1->setGeometry(QRect(100, 350, 40, 40));
        cell_6_1->setMaxLength(1);
        cell_6_1->setAlignment(Qt::AlignCenter);
        cell_6_3 = new QLineEdit(centralwidget);
        cell_6_3->setObjectName(QString::fromUtf8("cell_6_3"));
        cell_6_3->setGeometry(QRect(210, 350, 40, 40));
        cell_6_3->setMaxLength(1);
        cell_6_3->setAlignment(Qt::AlignCenter);
        cell_7_5 = new QLineEdit(centralwidget);
        cell_7_5->setObjectName(QString::fromUtf8("cell_7_5"));
        cell_7_5->setGeometry(QRect(310, 400, 40, 40));
        cell_7_5->setMaxLength(1);
        cell_7_5->setAlignment(Qt::AlignCenter);
        cell_7_2 = new QLineEdit(centralwidget);
        cell_7_2->setObjectName(QString::fromUtf8("cell_7_2"));
        cell_7_2->setGeometry(QRect(150, 400, 40, 40));
        cell_7_2->setMaxLength(1);
        cell_7_2->setAlignment(Qt::AlignCenter);
        cell_8_5 = new QLineEdit(centralwidget);
        cell_8_5->setObjectName(QString::fromUtf8("cell_8_5"));
        cell_8_5->setGeometry(QRect(310, 450, 40, 40));
        cell_8_5->setMaxLength(1);
        cell_8_5->setAlignment(Qt::AlignCenter);
        cell_8_7 = new QLineEdit(centralwidget);
        cell_8_7->setObjectName(QString::fromUtf8("cell_8_7"));
        cell_8_7->setGeometry(QRect(420, 450, 40, 40));
        cell_8_7->setMaxLength(1);
        cell_8_7->setAlignment(Qt::AlignCenter);
        cell_6_6 = new QLineEdit(centralwidget);
        cell_6_6->setObjectName(QString::fromUtf8("cell_6_6"));
        cell_6_6->setGeometry(QRect(370, 350, 40, 40));
        cell_6_6->setMaxLength(1);
        cell_6_6->setAlignment(Qt::AlignCenter);
        cell_7_6 = new QLineEdit(centralwidget);
        cell_7_6->setObjectName(QString::fromUtf8("cell_7_6"));
        cell_7_6->setGeometry(QRect(370, 400, 40, 40));
        cell_7_6->setMaxLength(1);
        cell_7_6->setAlignment(Qt::AlignCenter);
        cell_7_4 = new QLineEdit(centralwidget);
        cell_7_4->setObjectName(QString::fromUtf8("cell_7_4"));
        cell_7_4->setGeometry(QRect(260, 400, 40, 40));
        cell_7_4->setMaxLength(1);
        cell_7_4->setAlignment(Qt::AlignCenter);
        cell_8_0 = new QLineEdit(centralwidget);
        cell_8_0->setObjectName(QString::fromUtf8("cell_8_0"));
        cell_8_0->setGeometry(QRect(50, 450, 40, 40));
        cell_8_0->setMaxLength(1);
        cell_8_0->setAlignment(Qt::AlignCenter);
        cell_8_4 = new QLineEdit(centralwidget);
        cell_8_4->setObjectName(QString::fromUtf8("cell_8_4"));
        cell_8_4->setGeometry(QRect(260, 450, 40, 40));
        cell_8_4->setMaxLength(1);
        cell_8_4->setAlignment(Qt::AlignCenter);
        cell_7_1 = new QLineEdit(centralwidget);
        cell_7_1->setObjectName(QString::fromUtf8("cell_7_1"));
        cell_7_1->setGeometry(QRect(100, 400, 40, 40));
        cell_7_1->setMaxLength(1);
        cell_7_1->setAlignment(Qt::AlignCenter);
        cell_6_7 = new QLineEdit(centralwidget);
        cell_6_7->setObjectName(QString::fromUtf8("cell_6_7"));
        cell_6_7->setGeometry(QRect(420, 350, 40, 40));
        cell_6_7->setMaxLength(1);
        cell_6_7->setAlignment(Qt::AlignCenter);
        cell_6_2 = new QLineEdit(centralwidget);
        cell_6_2->setObjectName(QString::fromUtf8("cell_6_2"));
        cell_6_2->setGeometry(QRect(150, 350, 40, 40));
        cell_6_2->setMaxLength(1);
        cell_6_2->setAlignment(Qt::AlignCenter);
        cell_7_3 = new QLineEdit(centralwidget);
        cell_7_3->setObjectName(QString::fromUtf8("cell_7_3"));
        cell_7_3->setGeometry(QRect(210, 400, 40, 40));
        cell_7_3->setMaxLength(1);
        cell_7_3->setAlignment(Qt::AlignCenter);
        cell_8_8 = new QLineEdit(centralwidget);
        cell_8_8->setObjectName(QString::fromUtf8("cell_8_8"));
        cell_8_8->setGeometry(QRect(470, 450, 40, 40));
        cell_8_8->setMaxLength(1);
        cell_8_8->setAlignment(Qt::AlignCenter);
        cell_7_7 = new QLineEdit(centralwidget);
        cell_7_7->setObjectName(QString::fromUtf8("cell_7_7"));
        cell_7_7->setGeometry(QRect(420, 400, 40, 40));
        cell_7_7->setMaxLength(1);
        cell_7_7->setAlignment(Qt::AlignCenter);
        cell_7_8 = new QLineEdit(centralwidget);
        cell_7_8->setObjectName(QString::fromUtf8("cell_7_8"));
        cell_7_8->setGeometry(QRect(470, 400, 40, 40));
        cell_7_8->setMaxLength(1);
        cell_7_8->setAlignment(Qt::AlignCenter);
        cell_6_4 = new QLineEdit(centralwidget);
        cell_6_4->setObjectName(QString::fromUtf8("cell_6_4"));
        cell_6_4->setGeometry(QRect(260, 350, 40, 40));
        cell_6_4->setMaxLength(1);
        cell_6_4->setAlignment(Qt::AlignCenter);
        cell_6_8 = new QLineEdit(centralwidget);
        cell_6_8->setObjectName(QString::fromUtf8("cell_6_8"));
        cell_6_8->setGeometry(QRect(470, 350, 40, 40));
        cell_6_8->setMaxLength(1);
        cell_6_8->setAlignment(Qt::AlignCenter);
        cell_8_1 = new QLineEdit(centralwidget);
        cell_8_1->setObjectName(QString::fromUtf8("cell_8_1"));
        cell_8_1->setGeometry(QRect(100, 450, 40, 40));
        cell_8_1->setMaxLength(1);
        cell_8_1->setAlignment(Qt::AlignCenter);
        cell_8_3 = new QLineEdit(centralwidget);
        cell_8_3->setObjectName(QString::fromUtf8("cell_8_3"));
        cell_8_3->setGeometry(QRect(210, 450, 40, 40));
        cell_8_3->setMaxLength(1);
        cell_8_3->setAlignment(Qt::AlignCenter);
        cell_8_6 = new QLineEdit(centralwidget);
        cell_8_6->setObjectName(QString::fromUtf8("cell_8_6"));
        cell_8_6->setGeometry(QRect(370, 450, 40, 40));
        cell_8_6->setMaxLength(1);
        cell_8_6->setAlignment(Qt::AlignCenter);
        line = new QFrame(centralwidget);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(40, 170, 471, 16));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(centralwidget);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(190, 20, 20, 471));
        line_3->setFrameShape(QFrame::VLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(centralwidget);
        line_4->setObjectName(QString::fromUtf8("line_4"));
        line_4->setGeometry(QRect(350, 20, 20, 471));
        line_4->setFrameShape(QFrame::VLine);
        line_4->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(centralwidget);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(40, 330, 471, 16));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        backButton = new QPushButton(centralwidget);
        backButton->setObjectName(QString::fromUtf8("backButton"));
        backButton->setGeometry(QRect(230, 520, 75, 23));
        GameWindow->setCentralWidget(centralwidget);
        line_2->raise();
        cell_0_0->raise();
        cell_0_1->raise();
        cell_0_2->raise();
        cell_0_3->raise();
        cell_0_4->raise();
        cell_0_5->raise();
        cell_0_6->raise();
        cell_0_7->raise();
        cell_0_8->raise();
        cell_1_6->raise();
        cell_1_0->raise();
        cell_1_1->raise();
        cell_1_2->raise();
        cell_1_7->raise();
        cell_1_4->raise();
        cell_1_8->raise();
        cell_1_3->raise();
        cell_1_5->raise();
        cell_2_6->raise();
        cell_2_0->raise();
        cell_2_1->raise();
        cell_2_2->raise();
        cell_2_7->raise();
        cell_2_4->raise();
        cell_2_8->raise();
        cell_2_3->raise();
        cell_2_5->raise();
        cell_3_5->raise();
        cell_3_0->raise();
        cell_4_0->raise();
        cell_5_2->raise();
        cell_3_1->raise();
        cell_3_3->raise();
        cell_4_5->raise();
        cell_4_2->raise();
        cell_5_5->raise();
        cell_5_7->raise();
        cell_3_6->raise();
        cell_4_6->raise();
        cell_4_4->raise();
        cell_5_0->raise();
        cell_5_4->raise();
        cell_4_1->raise();
        cell_3_7->raise();
        cell_3_2->raise();
        cell_4_3->raise();
        cell_5_8->raise();
        cell_4_7->raise();
        cell_4_8->raise();
        cell_3_4->raise();
        cell_3_8->raise();
        cell_5_1->raise();
        cell_5_3->raise();
        cell_5_6->raise();
        cell_6_5->raise();
        cell_6_0->raise();
        cell_7_0->raise();
        cell_8_2->raise();
        cell_6_1->raise();
        cell_6_3->raise();
        cell_7_5->raise();
        cell_7_2->raise();
        cell_8_5->raise();
        cell_8_7->raise();
        cell_6_6->raise();
        cell_7_6->raise();
        cell_7_4->raise();
        cell_8_0->raise();
        cell_8_4->raise();
        cell_7_1->raise();
        cell_6_7->raise();
        cell_6_2->raise();
        cell_7_3->raise();
        cell_8_8->raise();
        cell_7_7->raise();
        cell_7_8->raise();
        cell_6_4->raise();
        cell_6_8->raise();
        cell_8_1->raise();
        cell_8_3->raise();
        cell_8_6->raise();
        line->raise();
        line_3->raise();
        line_4->raise();
        backButton->raise();
        menubar = new QMenuBar(GameWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 562, 21));
        menuFile = new QMenu(menubar);
        menuFile->setObjectName(QString::fromUtf8("menuFile"));
        menuHelp = new QMenu(menubar);
        menuHelp->setObjectName(QString::fromUtf8("menuHelp"));
        GameWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(GameWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        GameWindow->setStatusBar(statusbar);
        QWidget::setTabOrder(cell_0_0, cell_0_1);
        QWidget::setTabOrder(cell_0_1, cell_0_2);
        QWidget::setTabOrder(cell_0_2, cell_0_3);
        QWidget::setTabOrder(cell_0_3, cell_0_4);
        QWidget::setTabOrder(cell_0_4, cell_0_5);
        QWidget::setTabOrder(cell_0_5, cell_0_6);
        QWidget::setTabOrder(cell_0_6, cell_0_7);
        QWidget::setTabOrder(cell_0_7, cell_0_8);
        QWidget::setTabOrder(cell_0_8, cell_1_0);
        QWidget::setTabOrder(cell_1_0, cell_1_1);
        QWidget::setTabOrder(cell_1_1, cell_1_2);
        QWidget::setTabOrder(cell_1_2, cell_1_3);
        QWidget::setTabOrder(cell_1_3, cell_1_4);
        QWidget::setTabOrder(cell_1_4, cell_1_5);
        QWidget::setTabOrder(cell_1_5, cell_1_6);
        QWidget::setTabOrder(cell_1_6, cell_1_7);
        QWidget::setTabOrder(cell_1_7, cell_1_8);
        QWidget::setTabOrder(cell_1_8, cell_2_0);
        QWidget::setTabOrder(cell_2_0, cell_2_1);
        QWidget::setTabOrder(cell_2_1, cell_2_2);
        QWidget::setTabOrder(cell_2_2, cell_2_3);
        QWidget::setTabOrder(cell_2_3, cell_2_4);
        QWidget::setTabOrder(cell_2_4, cell_2_5);
        QWidget::setTabOrder(cell_2_5, cell_2_6);
        QWidget::setTabOrder(cell_2_6, cell_2_7);
        QWidget::setTabOrder(cell_2_7, cell_2_8);
        QWidget::setTabOrder(cell_2_8, cell_3_0);
        QWidget::setTabOrder(cell_3_0, cell_3_1);
        QWidget::setTabOrder(cell_3_1, cell_3_2);
        QWidget::setTabOrder(cell_3_2, cell_3_3);
        QWidget::setTabOrder(cell_3_3, cell_3_4);
        QWidget::setTabOrder(cell_3_4, cell_3_5);
        QWidget::setTabOrder(cell_3_5, cell_3_6);
        QWidget::setTabOrder(cell_3_6, cell_3_7);
        QWidget::setTabOrder(cell_3_7, cell_3_8);
        QWidget::setTabOrder(cell_3_8, cell_4_0);
        QWidget::setTabOrder(cell_4_0, cell_4_1);
        QWidget::setTabOrder(cell_4_1, cell_4_2);
        QWidget::setTabOrder(cell_4_2, cell_4_3);
        QWidget::setTabOrder(cell_4_3, cell_4_4);
        QWidget::setTabOrder(cell_4_4, cell_4_5);
        QWidget::setTabOrder(cell_4_5, cell_4_6);
        QWidget::setTabOrder(cell_4_6, cell_4_7);
        QWidget::setTabOrder(cell_4_7, cell_4_8);
        QWidget::setTabOrder(cell_4_8, cell_5_0);
        QWidget::setTabOrder(cell_5_0, cell_5_1);
        QWidget::setTabOrder(cell_5_1, cell_5_2);
        QWidget::setTabOrder(cell_5_2, cell_5_3);
        QWidget::setTabOrder(cell_5_3, cell_5_4);
        QWidget::setTabOrder(cell_5_4, cell_5_5);
        QWidget::setTabOrder(cell_5_5, cell_5_6);
        QWidget::setTabOrder(cell_5_6, cell_5_7);
        QWidget::setTabOrder(cell_5_7, cell_5_8);
        QWidget::setTabOrder(cell_5_8, cell_6_0);
        QWidget::setTabOrder(cell_6_0, cell_6_1);
        QWidget::setTabOrder(cell_6_1, cell_6_2);
        QWidget::setTabOrder(cell_6_2, cell_6_3);
        QWidget::setTabOrder(cell_6_3, cell_6_4);
        QWidget::setTabOrder(cell_6_4, cell_6_5);
        QWidget::setTabOrder(cell_6_5, cell_6_6);
        QWidget::setTabOrder(cell_6_6, cell_6_7);
        QWidget::setTabOrder(cell_6_7, cell_6_8);
        QWidget::setTabOrder(cell_6_8, cell_7_0);
        QWidget::setTabOrder(cell_7_0, cell_7_1);
        QWidget::setTabOrder(cell_7_1, cell_7_2);
        QWidget::setTabOrder(cell_7_2, cell_7_3);
        QWidget::setTabOrder(cell_7_3, cell_7_4);
        QWidget::setTabOrder(cell_7_4, cell_7_5);
        QWidget::setTabOrder(cell_7_5, cell_7_6);
        QWidget::setTabOrder(cell_7_6, cell_7_7);
        QWidget::setTabOrder(cell_7_7, cell_7_8);
        QWidget::setTabOrder(cell_7_8, cell_8_0);
        QWidget::setTabOrder(cell_8_0, cell_8_1);
        QWidget::setTabOrder(cell_8_1, cell_8_2);
        QWidget::setTabOrder(cell_8_2, cell_8_3);
        QWidget::setTabOrder(cell_8_3, cell_8_4);
        QWidget::setTabOrder(cell_8_4, cell_8_5);
        QWidget::setTabOrder(cell_8_5, cell_8_6);
        QWidget::setTabOrder(cell_8_6, cell_8_7);
        QWidget::setTabOrder(cell_8_7, cell_8_8);

        menubar->addAction(menuFile->menuAction());
        menubar->addAction(menuHelp->menuAction());
        menuFile->addAction(actionNew_Game);
        menuFile->addAction(actionSave);
        menuFile->addSeparator();
        menuFile->addAction(actionSave_and_Exit);
        menuFile->addAction(actionExit);
        menuHelp->addAction(actionHow_To_Play);

        retranslateUi(GameWindow);

        QMetaObject::connectSlotsByName(GameWindow);
    } // setupUi

    void retranslateUi(QMainWindow *GameWindow)
    {
        GameWindow->setWindowTitle(QApplication::translate("GameWindow", "Sudoku", 0, QApplication::UnicodeUTF8));
        actionNew_Game->setText(QApplication::translate("GameWindow", "New Game", 0, QApplication::UnicodeUTF8));
        actionNew_Game->setShortcut(QApplication::translate("GameWindow", "Ctrl+N", 0, QApplication::UnicodeUTF8));
        actionSave->setText(QApplication::translate("GameWindow", "Save", 0, QApplication::UnicodeUTF8));
        actionSave->setShortcut(QApplication::translate("GameWindow", "Ctrl+S", 0, QApplication::UnicodeUTF8));
        actionSave_and_Exit->setText(QApplication::translate("GameWindow", "Save and Exit", 0, QApplication::UnicodeUTF8));
        actionExit->setText(QApplication::translate("GameWindow", "Exit", 0, QApplication::UnicodeUTF8));
        actionHow_To_Play->setText(QApplication::translate("GameWindow", "How To Play", 0, QApplication::UnicodeUTF8));
        backButton->setText(QApplication::translate("GameWindow", "Main Menu", 0, QApplication::UnicodeUTF8));
        menuFile->setTitle(QApplication::translate("GameWindow", "File", 0, QApplication::UnicodeUTF8));
        menuHelp->setTitle(QApplication::translate("GameWindow", "Help", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class GameWindow: public Ui_GameWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_GAMEWINDOW_H
